### PR TITLE
Upgrade `is-admin` to v2.1.0

### PR DESCRIPTION
**Pull request by jviotti**
Signed-off-by: Juan Cruz Viotti <jviotti@openmailbox.org>

### CODE REVIEW

**Comment by sindresorhus** [comment]
Thanks, but I decided to switch to a Promise interface while I was at it.

**Comment by jviotti** [comment]
Sounds good, thanks a lot!

**Comment by jviotti** [comment]
@sindresorhus `is-root` doesn't return a promise. Looks like we should do `Promise.resolve(isRoot())`.

**Comment by sindresorhus** [comment]
Sorry, I forgot about that and the test was faulty. Fixed 2.0.1.

**Comment by jviotti** [comment]
Thanks a lot again!

**Pull request closed without merging**
